### PR TITLE
Added solution to No Idea! problem in Python/04. Sets folder

### PR DESCRIPTION
**Pull request by ShivayeModi**
### Issue Number: #152

This submission will close the issue #

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

 https://www.hackerrank.com/challenges/no-idea/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:

 https://www.hackerrank.com/challenges/no-idea/submissions/code/293725784

### Any other changes you made or something you would like to mention?

 NA

### CODE REVIEW

**Comment by Riddhi9570** [comment]
@ShivayeModi Please mention the issue you are referring to, so that I can review. Thanks!

**Comment by Riddhi9570** [comment]
Ok, I got it #152

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
Thanks for contributing! Following change is requested before merging the PR:-

- Please add the required comments at the top of your solution as mentioned in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md).

**Comment by ShivayeModi** [comment]
Hi @Riddhi9570 , I have added the comments at top of my solution at my end . Is it visible at your end or do I have to make another pull request?

**Comment by Riddhi9570** [comment]
@ShivayeModi No need to make a new PR since all the commits are added in the opened PR.

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for contributing!

**Pull request merged**
