### PR TITLE
Python String Validators

### PR DESCRIPTION
**Pull request by saikishore222**
Python program to test the string with string validators

### Issue Number: #125 

This submission will close the issue #125 

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

Yes, I am Hactoberfest Contributor

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/string-validators/problem

### Submitted Hackerrank Solution Link:

submission link here-->

https://www.hackerrank.com/challenges/string-validators/submissions/code/293711272

### CODE REVIEW

**Comment by saikishore222** [comment]
@Riddhi9570  My PR is ready for review.

**Review by Riddhi9570 — APPROVED** [review]
@saikishore222  Thanks for contributing! Following change is requested before merging the PR:-

- Please move the file inside the Strings folder of Python.

**Comment by saikishore222** [comment]
> @saikishore222 Thanks for contributing! Following change is requested before merging the PR:-
> 
> * Please move the file inside the Strings folder of Python.
Thank, sure

**Comment by saikishore222** [comment]
> @saikishore222 Thanks for contributing! Following change is requested before merging the PR:-
> 
> * Please move the file inside the Strings folder of Python.

I updated the repo , can you please review it again.

**Review by Riddhi9570 — APPROVED** [review]
@saikishore222 Great! Thanks for contributing!

**Pull request merged**
