### PR TITLE
Solution for #19 Java HackerRank problem

### PR DESCRIPTION
**Pull request by AmanGit010**
### Issue Number:

This submission will close the issue #

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/welcome-to-java/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/welcome-to-java/submissions/code/293570694

### Any other changes you made or something you would like to mention?

NA

### CODE REVIEW

**Comment by AmanGit010** [comment]
@Riddhi9570 please check if the file name is correct and let me know if there is a change to be done.

**Comment by Riddhi9570** [comment]
> @Riddhi9570 please check if the file name is correct and let me know if there is a change to be done.

@AmanGit010 Thanks for contributing! following changes are requested:-

- Update your repo from the origin remote.
- Rename your file and give spaces between the words.
- Provide the hackerrank problem link and the submitted solution link in the PR for review.

**Comment by AmanGit010** [comment]
@Riddhi9570 I have made the changes.

**Review by Riddhi9570 — APPROVED** [review]
@AmanGit010 Great! Thanks for contributing!

**Comment by AmanGit010** [comment]
@Riddhi9570 Thank you for helping me out and letting me contribute to this great repo!

**Pull request merged**
