### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by parth-verma7**
### Issue Number:

This submission will close the issue #

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### CODE REVIEW

**Comment by Riddhi9570** [comment]
hi @parth-verma7 Please mention the issue you are referring to, so that I can review. Thanks!

**Comment by parth-verma7** [comment]
@Riddhi9570 I have Fixed #33, Please review the PR.

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
Thanks for contributing! Following changes are requested before merging the PR:-

- Please add the required comments at the top of your solution as mentioned in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md).
- Rename the file as "Interviews.sql".

**Comment by parth-verma7** [comment]
@Riddhi9570  I have done all the changes , please review.

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for contributing!

**Pull request merged**
