### PR TITLE
 C++ : StringStream #17 

### PR DESCRIPTION
**Pull request by Csrivastava003**
### Issue Number:

This submission will close the issue #

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/c-tutorial-stringstream/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/c-tutorial-stringstream/submissions/code/293434077

### Any other changes you made or something you would like to mention?
NA

### CODE REVIEW

**Comment by Riddhi9570** [comment]
Hey @Csrivastava003 , please do let me know which issue you are referring to?

**Comment by Csrivastava003** [comment]
> 

# Issue 17

**Comment by Riddhi9570** [comment]
@Csrivastava003 This branch has conflicts that must be resolved

**Comment by Csrivastava003** [comment]
> @Csrivastava003
> 
>     * This branch has conflicts that must be resolved
> 
>     * Keep your forked repo up-to-date with the original repo.

I should create a new pr with resolved conflicts?

**Pull request closed without merging**
