### PR TITLE
functions C++ solution

### PR DESCRIPTION
**Pull request by Amarendra-ai**
### Issue Number: #13 

This submission will close the issue #13 

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/c-tutorial-functions/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/c-tutorial-functions/submissions/code/293765530

### CODE REVIEW

**Comment by Amarendra-ai** [comment]
solved issue #13

**Review by Riddhi9570 — APPROVED** [review]
@Amarendra-ai Thanks for contributing! Following changes are requested before merging the PR:-
- Provide the hackerrank problem link and the submitted solution link in the PR for review.
- Update your forked repo with the origin remote and check that the files are in the appropriate folder.

**Comment by Amarendra-ai** [comment]
> @Amarendra-ai Thanks for contributing! Following changes are requested before merging the PR:-
> 
>     * Provide the hackerrank problem link and the submitted solution link in the PR for review.
> 
>     * Update your forked repo with the origin remote and check that the files are in the appropriate folder.



> @Amarendra-ai Thanks for contributing! Following changes are requested before merging the PR:-
> 
>     * Provide the hackerrank problem link and the submitted solution link in the PR for review.
> 
>     * Update your forked repo with the origin remote and check that the files are in the appropriate folder.

done

**Comment by Amarendra-ai** [comment]
> @Amarendra-ai Thanks for contributing! Following changes are requested before merging the PR:-
> 
>     * Provide the hackerrank problem link and the submitted solution link in the PR for review.
> 
>     * Update your forked repo with the origin remote and check that the files are in the appropriate folder.

done

**Pull request closed without merging**
