### PR TITLE
Added operator_overloading.cpp

### PR DESCRIPTION
**Pull request by PurviSaini**
### Issue Number: 87

This submission will close the issue #87

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link: 

https://www.hackerrank.com/challenges/operator-overloading/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:
https://www.hackerrank.com/challenges/operator-overloading/submissions/code/293573254

### Any other changes you made or something you would like to mention?

NA

### CODE REVIEW

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
@PurviSaini Thanks for contributing! Following changes are requested before merging :-

- Please rename your file to "Operator Overloading.cpp".
- Since this question comes under the subdomain "Other Concepts" in hackerrank, please move it to the folder "Other Concepts" inside the "C++" folder. If this folder is not present, please create a new folder with this name.

**Comment by PurviSaini** [comment]
I have made the required changes. Are they visible?

**Comment by Riddhi9570** [comment]
> I have made the required changes. Are they visible?

@PurviSaini Sorry, It is not visible to me. Also make sure that your repo is up-to-date with the origin remote.

**Comment by PurviSaini** [comment]
Do I need to create another PR for this update?

**Comment by PurviSaini** [comment]
I have made the required changes in the branch issue87, the changes are visible on my side

**Review by Riddhi9570 — APPROVED** [review]

**Comment by Riddhi9570** [comment]
Great!  it's fine now, Thanks for contributing!

**Comment by PurviSaini** [comment]
Thankyou so much!!

**Pull request merged**
