### PR TITLE
The power sum python solution

### PR DESCRIPTION
**Pull request by achiverram28**
### Issue Number:

This submission closes # issue

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### CODE REVIEW

**Review by Riddhi9570 — APPROVED** [review]
Thanks for contributing! Following changes are requested before merging the PR:-
- Please add the required comments at the top of your solution as mentioned in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md).
- Please mention the issue.

**Comment by achiverram28** [comment]
I have updated , please approve it

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for contributing!

**Comment by achiverram28** [comment]
Hey thanks for giving the opportunity , I am grateful . But one thing why is this project excluded from the hacktoberfest

**Comment by Riddhi9570** [comment]
Thanks for asking. Probably because I approved lots of PRs from this repo in last 2-3 days for hacktoberfest and according to the values of hacktoberfest, the project should be valuable and does not accept the small contributions just for completing the hacktoberfest task, like changing the README.md, etc. Few of them did so which was against the value of hacktoberfest. I don't know the exact reason because they didn't sent me the mail for it, I just got to know it from the contributors that their PRs are marked as excluded in the hacktoberfest.

**Pull request merged**
