### PR TITLE
Created Variable sized arrays-cpp

### PR DESCRIPTION
**Pull request by Prahmodh-R**
### Issue Number: 16

This submission will close the issue #16 

### Submissions Checklist:

- [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
- [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
- [x] Have you successfully submitted your code in hackerrank?
- [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
- [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

- [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/variable-sized-arrays/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/variable-sized-arrays/submissions/code/293436026

### CODE REVIEW

**Comment by Prahmodh-R** [comment]
@Riddhi9570 I'm not able to make the Pull request as it says that a review is required and merging is blocked. Could you please help me out in resolving this

**Comment by Riddhi9570** [comment]
> @Riddhi9570 I'm not able to make the Pull request as it says that a review is required and merging is blocked. I think there's a mistake in marking the checklist. Could you please guide me on how I could mark the items in checklist as this is new to me?

Hey @Prahmodh-R Thanks for asking! There is no mistake in marking the checklist. This kind of statement is given when a review is required by the owner or maintainer of the PR. Once it is reviewed, it can be merged. You just have to create the PR and wait for the review and merge. Hope you understand. Thanks!

**Comment by Prahmodh-R** [comment]
@Riddhi9570 Thanks for clarifying:)

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
@Prahmodh-R Nice job! Only one change is requested. Please add the score and difficulty level of the hackerrank problem at the top of your solution as comment like [this](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/SQL/1.%20BASIC%20SELECT/01.%20Revising%20the%20Select%20Query%20I.sql)

**Comment by Prahmodh-R** [comment]
@Riddhi9570 I've added the score and Difficulty level of the problem, Could you please check now

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for contributing!

**Pull request merged**
