### PR TITLE
solves arrays introduction

### PR DESCRIPTION
**Pull request by akshatjain1004**
### Issue Number:

This submission will close the issue #15 

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/arrays-introduction/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/arrays-introduction/submissions/code/293511119

# Score : 10
# Difficulty: Easy

### CODE REVIEW

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
Nice job @akshatjain1004. Thanks for contributing! Only one change is requested:- 
- Please add the difficulty level and max score as comment at the top of your solution like [this](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/SQL/1.%20BASIC%20SELECT/03.%20Select%20All.sql).

**Comment by akshatjain1004** [comment]
> Nice job @akshatjain1004. Thanks for contributing! Only one change is requested:-
> 
> * Please add the difficulty level and max score as comment at the top of your solution like [this](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/SQL/1.%20BASIC%20SELECT/03.%20Select%20All.sql).

Done !

**Comment by Ashasindhu** [comment]
can you please tell  me how to add checklist in the comments

**Comment by Riddhi9570** [comment]
> can you please tell me how to add checklist in the comments

@Ashasindhu For that, you need to write [x] to mark the checklist.

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for your contribution!

**Pull request merged**
