### PR TITLE
Algorithims

### PR DESCRIPTION
**Pull request by sasidharswarangi**
### Issue Number:

This submission will close the issue #194  

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/coin-change/problem?isFullScreen=true
https://www.hackerrank.com/challenges/equal/problem?isFullScreen=true
https://www.hackerrank.com/challenges/stockmax/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/coin-change/submissions/code/293802088
https://www.hackerrank.com/challenges/equal/submissions/code/293801966
https://www.hackerrank.com/challenges/stockmax/submissions/code/293799979

### Any other changes you made or something you would like to mention?

A lot more problems and topics are available under Algorithms  for example greedy, etc

### CODE REVIEW

**Review by Riddhi9570 — APPROVED** [review]
Nice work! just do one thing, add comments at the top of your solution as mentioned in Contributing.md before this gets merged.

**Comment by sasidharswarangi** [comment]
can you add hactober 2022 tag

**Comment by sasidharswarangi** [comment]
added comments as requested

**Review by Riddhi9570 — COMMENTED** [review]
Thanks for adding the appropriate comments for your codes. Along with these, at the top, please add problem link, problem name, score, subdomain and language as comment.

**Comment by sasidharswarangi** [comment]
added the link, score, difficulty rating as requested, subdomain and language are understandable as it's under Dynamic programming, and its a .CPP file

**Comment by sasidharswarangi** [comment]
re requesting for merging as everything is added

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for your valuable contribution!

**Pull request merged**
