### PR TITLE
Solution of Java Interface problem by Aditya

### PR DESCRIPTION
**Pull request by adityjoshi**
### Issue Number: #72 

This submission will close the issue # #72

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?
yes 
### Hackerrank Problem Link:

 https://www.hackerrank.com/challenges/java-interface/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/java-interface/submissions/code/293731706

### Any other changes you made or something you would like to mention?
na

### CODE REVIEW

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
@adityjoshi Thanks for contributing! Following change is requested before merging:-
- Update your forked repo with the origin repo and move the file in Object Oriented Folder inside the Java folder.

**Comment by Riddhi9570** [comment]
Hey @adityjoshi. It is not needed to delete the forked repo and close the PR. You could have just make the changes and all the commits would appear here in the opened PR for review. Thanks!

**Comment by adityjoshi** [comment]
@Riddhi9570 well sorry for that can you do one thing just remove the space between object oriented programming make it like this 
objectorientedprogramming or oops

**Comment by Riddhi9570** [comment]
> @Riddhi9570 well sorry for that can you do one thing just remove the space between object oriented programming make it like this objectorientedprogramming or oops

Sorry, this is not the change requested. Well, no issue, I'll move the file in the appropriate folder. Thanks for contributing!

**Review by Riddhi9570 — APPROVED** [review]

**Comment by adityjoshi** [comment]
Hey @Riddhi9570 thank you , now can u assign me the previous issue I asked for 😅

**Comment by Riddhi9570** [comment]
Hey @adityjoshi unfortunately, I can assign max of two issues to the same contributor in this repo for hacktoberfest.

**Pull request merged**
