### PR TITLE
Added Runner-Up Score

### PR DESCRIPTION
**Pull request by yashkc2025**
### Issue Number:

This submission will close the issue #148 

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/submissions/code/275202854

### Any other changes you made or something you would like to mention?

NA

### CODE REVIEW

**Review by Riddhi9570 — APPROVED** [review]
@yashkc2025 Thanks for contributing! Following changes are requested before merging the PR:-

- Please add the required comments at the top of your solution as mentioned in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md).
- Move the file in the appropriate folder.

**Comment by yashkc2025** [comment]
You already merged someone else's solution for this problem. Hence, i am closing the request.

**Comment by Riddhi9570** [comment]
> You already merged someone else's solution for this problem. Hence, i am closing the request.

OOps, you should have checked if it was present before. No worries, you can raise a new issue for another problem. Thanks!

**Comment by yashkc2025** [comment]
It was actually added yesterday by someone.

**Pull request closed without merging**
