### PR TITLE
added Hello world program in C++

### PR DESCRIPTION
**Pull request by sumitbishti**
### Issue Number: 8

This submission will close the issue #8 

### Submissions Checklist:

* [✓] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [ ✓] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [✓] Have you successfully submitted your code in hackerrank?
* [✓] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [✓] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [✓] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/cpp-hello-world/problem

### Submitted Hackerrank Solution Link:

(https://www.hackerrank.com/challenges/cpp-hello-world/submissions/code/293522996)

### CODE REVIEW

**Review by Riddhi9570 — COMMENTED** [review]
@sumitbishti Please follow the [pull_request_template.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/.github/pull_request_template.md)

**Comment by sumitbishti** [comment]
@Riddhi9570 corrected it. Kindly review.

**Comment by Riddhi9570** [comment]
@sumitbishti Thanks! One more change is requested, please add the problem link, score, and difficulty as comment at the top of your solution like [this](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/SQL/1.%20BASIC%20SELECT/09.%20Weather%20Observation%20Station%204.sql)

**Comment by sumitbishti** [comment]
> @sumitbishti Thanks! One more change is requested, please add the problem link, score, and difficulty as comment at the top of your solution like [this](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/SQL/1.%20BASIC%20SELECT/09.%20Weather%20Observation%20Station%204.sql)

It's done!

**Review by Riddhi9570 — APPROVED** [review]
@sumitbishti Great! Thanks for contributing!

**Pull request merged**
