### PR TITLE
Create Vector Erase STL

### PR DESCRIPTION
**Pull request by manish831**
I thought, this problem with code must be in repo.

### Issue Number:

This submission will close the issue #

### Submissions Checklist:

* [ ] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [ ] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [ ] Have you successfully submitted your code in hackerrank?
* [ ] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [ ] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [ ] Are you a hacktoberfest contributor?

### CODE REVIEW

**Comment by Riddhi9570** [comment]
@manish831 Thanks for contributing! But you should have first raised an issue before making a PR. And once it gets assigned to you, then start working on it. This is considered a good practice for contributing to any open source project. Hope you understand. Happy Coding😃!

**Comment by manish831** [comment]
#143  this issue is resolved.

Plz do merge it now @Riddhi9570

**Review by Riddhi9570 — CHANGES_REQUESTED** [review]
@manish831 
Thanks for contributing! Following changes are requested before merging the PR:-

- Please add the score and difficulty level as a comment at the top of your solution like [this](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/SQL/1.%20BASIC%20SELECT/01.%20Revising%20the%20Select%20Query%20I.sql).
- Provide the hackerrank problem link and the submitted solution link in the PR for review.
- Update your forked repo from the origin remote and check that the file is in the appropriate folder.
- Please follow and mark the checklists given in PR template.

**Comment by manish831** [comment]
@Riddhi9570 , now you can check my branch.
It's follows all the guidelines, plz merge it.

**Review by Riddhi9570 — APPROVED** [review]

**Pull request merged**
