### PR TITLE
Solution to JAVA 1D Array added

### PR DESCRIPTION
**Pull request by AditUB**
### Issue Number: #70 

This submission will close the issue #70 

### Submissions Checklist:

* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/java-1d-array-introduction/problem

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/java-1d-array-introduction/submissions/code/293661825

### Any other changes you made or something you would like to mention?

NA

### CODE REVIEW

**Review by Riddhi9570 — APPROVED** [review]
Nice Work! Thanks for contributing!

**Comment by AditUB** [comment]
Thank you for your time!

**Comment by AditUB** [comment]
Can I contribute more to this repository?

**Comment by Riddhi9570** [comment]
> Can I contribute more to this repository?

If this was your first contribution to this repository, you can contribute max one more time to this repository. Thanks!

**Pull request merged**
