### PR TITLE
Added solution for #153 JAVA: Java Currency Formatter

### PR DESCRIPTION
**Pull request by AmanGit010**
### Issue Number:

This submission will close the issue #153 

### Submissions Checklist:

* [x] This issue was assigned to you.
* [x] Have you followed the guidelines in [CONTRIBUTING.md](https://github.com/Riddhi9570/HackerrankPracticeProblems/blob/main/CONTRIBUTING.md)?
* [x] Have you checked there aren't other open [Pull Requests](https://github.com/Riddhi9570/HackerrankPracticeProblems/pulls) for the same hackerrank problem?
* [x] Have you successfully submitted your code in hackerrank?
* [x] Is your file name exactly same as the problem name of hackerrank, followed by the proper extension?
* [x] Have you ensured that you have put the files in appropriate folders? (Folders are made according to the subdomain of hackerrank practice problems).

### Hacktoberfest Contributor:

* [x] Are you a hacktoberfest contributor?

### Hackerrank Problem Link:

https://www.hackerrank.com/challenges/java-currency-formatter/problem?isFullScreen=true

### Submitted Hackerrank Solution Link:

https://www.hackerrank.com/challenges/java-currency-formatter/submissions/code/293756384

### Any other changes you made or something you would like to mention?

NA

@Riddhi9570 Please let me know if there are any changes to be done.

### CODE REVIEW

**Comment by AmanGit010** [comment]
I hope my PRs qualify for hacktoberfest, @Riddhi9570 did someone's PR got qualified by Hacktoberfest?

**Review by Riddhi9570 — APPROVED** [review]
Great! Thanks for contributing!

**Comment by Riddhi9570** [comment]
> I hope my PRs qualify for hacktoberfest, @Riddhi9570 did someone's PR got qualified by Hacktoberfest?

Yes @AmanGit010 
For safer side, try to make more than 4 PRs in total for hacktoberfest from different repositories, in case some of them gets excluded for hacktoberfest.

**Comment by AmanGit010** [comment]
Okay @Riddhi9570 thanks!

**Pull request merged**
